# Credits

Most of the content of this notebook was taken from the Numpy's quickstart tutorial from the official documentation at
https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html ([Numpy License](http://www.numpy.org/license.html)), and adapted for a 2 hours workshop. 

The section **Views versus copies in NumPy** was adapted from the [scipy cookbook](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html).

# Table Of Contents

1. [What is NumPy?](#WhatIsNumpy)
1. [The Basics](#TheBasics)
1. [Array Creation](#ArrayCreation)
1. [Basic Operations](#BasicOperations)
1. [Aggregations: min, max, sum, prod, mean, std, var, any, all:](#Aggregations)
1. [Indexing, Slicing and Iterating](#Indexing)
1. [Views versus copies in NumPy](#Views)
1. [License and Credits](#License)


<a id='WhatIsNumpy'></a>
# What is NumPy?

**NumPy is the fundamental package for scientific computing in Python**. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and many routines for fast operations on arrays, including mathematical and logical operations, shape manipulation, sorting, selecting elements of an array, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulations and much more.

At the core of the NumPy package, is the **ndarray object**. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences (like lists or tuples):

* **NumPy arrays have a fixed size at creation**, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
* **The elements in a NumPy array are all required to be of the same data type**, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.


## Documentation

Numpy has a great online documantation, that covers its basics usage and the description of all the functions implemented.  

The latest documentation can be found at https://docs.scipy.org/doc/numpy/



<a id='TheBasics'></a>
# The Basics

**NumPy’s main object is the homogeneous multidimensional array**. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy, dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis (1D array). That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

```python
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
```

**NumPy’s array class is called ndarray**. It is also known by the alias array. *Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality.* The more important attributes of an ndarray object are:

* **ndarray.ndim** : the number of axes (dimensions) of the array.
* **ndarray.shape** : the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
* **ndarray.size** : the total number of elements of the array. This is equal to the product of the elements of shape.
* **ndarray.dtype** : an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
* **ndarray.itemsize**: the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
* **ndarray.data** : the buffer containing the actual elements of the array. **Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.**


## Examples


In [1]:
# Import the numpy module 
import numpy as np # Important!, here the numpy library is imported using the alias "np"

# Create an 1D array with 15 elements, evenly spaced from 0 to 14.
my_1D_array = np.arange(15)


# Create an 2D array by reshaping the 1D array to a (3,5) shape.
my_2D_array = np.arange(15).reshape(3, 5)

print("my_1D_array:", my_1D_array, "\n")
print("my_2D_array:\n", my_2D_array , "\n")

# Number of dimensions 
print("my_2D_array ndim:", my_2D_array.ndim, "\n")

# Shape
print("my_2D_array shape:", my_2D_array.shape, "\n")

# Size (total number of elemnts)
print("my_2D_array size:", my_2D_array.size, "\n")

print("my_2D_array type:", type(my_2D_array))

my_1D_array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

my_2D_array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

my_2D_array ndim: 2 

my_2D_array shape: (3, 5) 

my_2D_array size: 15 

my_2D_array type: <class 'numpy.ndarray'>


<a id='ArrayCreation'></a>
# Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. 
**The elements data type of the resulting array is deduced from the data type of the elements in the sequences.**


In [2]:
# import numpy as np #imported before!

list_of_integers = [2,3,4]

my_array = np.array(list_of_integers)

print("my_array: ", my_array)
print("my_array dtype: ", my_array.dtype , "\n")


list_of_floats = [1.2, 3.5, 5.1]

other_array = np.array(list_of_floats)
print("other_array: ", other_array)
print("other_array dtype: ", other_array.dtype)


my_array:  [2 3 4]
my_array dtype:  int64 

other_array:  [ 1.2  3.5  5.1]
other_array dtype:  float64


A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

```python
a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
```

The array function transforms **sequences of sequences** into two-dimensional arrays, **sequences of sequences of sequences into three-dimensional arrays**, and so on.


In [3]:
list_of_lists =  [ [1.5,2,3] , [4,5,6] ]
my_2D_array = np.array(list_of_lists)

print("my_2D_array:\n\n", repr(my_2D_array))

# What is repr()??
# This functions returns the object's representation as an string.
# This representation is defined in the object __repr__ method.

my_2D_array:

 array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])


**The type of the array can also be explicitly specified at creation time.**

In [4]:
# The type of the array can also be explicitly specified at creation time:
my_2D_array_integer = np.array(list_of_lists, dtype='int')
my_2D_array_integer

array([[1, 2, 3],
       [4, 5, 6]])

### Array initialization
Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function **zeros** creates an array full of zeros, the function **ones** creates an array full of ones, and the function **empty** creates an array whose initial content is random and depends on the state of the memory.
Finally, the function **full** creates an array filled with given value. **By default, the dtype of the created array is float64.**

In [5]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
np.ones( (2,3,4), dtype=np.int16 ) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
np.empty( (2,3) )  # uninitialized, output may vary

array([[  2.32973918e-310,   5.30276956e+180,   5.05117710e-038],
       [  4.57046482e-071,   3.65882779e-086,   3.36009213e-143]])

In [8]:
np.full((2, 2), 10)  # Array of 10s

array([[10, 10],
       [10, 10]])

### arange function

To create sequences of numbers, **NumPy provides a function analogous to range that returns arrays instead of lists.**

The calling arguments for this function are: *arange([start, ]stop, [step, ]dtype=None)*, [see the documentation for more details](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.arange.html?highlight=arange#numpy.arange).

This function can be called in different ways: 
* **np.arange(stop)** : returns a sequence from 0 to stop-1 , with an step of 1.
* **np.arange(start,stop)** : returns a sequence from start to stop-1 , with an step of 1.
* **np.arange(start, stop, step)** :  : returns a sequence from start to stop-1 , with an step defined by the user.

The dtype keyword can be aso used to specify the desired data type of sequence.

For example:

In [9]:
np.arange( 10) # equivalent to np.arange(0,10) and np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [11]:
np.arange( 0, 2, 0.3 )  

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [12]:
np.arange( 10, 0, -1 )  

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### linspace function

When **arange** is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function **linspace** that receives as an argument the **number of elements that we want, instead of the step**.

The calling arguments for this function are: 
*numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)*, 
[see the documentation for more details](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace).

In [13]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [14]:
from numpy import pi

x = np.linspace( 0, 2*pi, 6 )        # useful to evaluate function at lots of points
print("x=",x,"\n")

f = np.sin(x)
print("sin(x)=",f)

x= [ 0.          1.25663706  2.51327412  3.76991118  5.02654825  6.28318531] 

sin(x)= [  0.00000000e+00   9.51056516e-01   5.87785252e-01  -5.87785252e-01
  -9.51056516e-01  -2.44929360e-16]


<a id='BasicOperations'></a>
# Basic Operations

Arithmetic operators on arrays apply elementwise. **A new array is created and filled with the result**.

In [15]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

c = a-b
c

array([20, 29, 38, 47])

In [16]:
b**2

array([0, 1, 4, 9])

In [17]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [18]:
a<35

array([ True,  True, False, False], dtype=bool)

Unlike in many matrix languages, **the product operator * operates elementwise in NumPy arrays**.

**The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:**

In [19]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

A * B # elementwise product

array([[2, 0],
       [0, 4]])

In [20]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [21]:
A.dot(B) # another matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, **act in place to modify an existing array rather than create a new one.**

In [22]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [23]:
b = np.random.random((2,3))
b += a
b

array([[ 3.13710734,  3.87017576,  3.31627414],
       [ 3.58724865,  3.85268502,  3.60743477]])

In [24]:
a += b # b is not automatically converted to integer type!!!

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

When operating with arrays of different types, **the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting)**.

In [25]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

c = a+b
c.dtype

dtype('float64')

<a id='Aggregations'></a>
# Aggregations: min, max, sum, prod, mean, std, var, any, all

We commonly need to compute statistics on a large amount of data. NumPy has fast built-in aggregation functions to compute the following statistics:

* min : Return the minimum along a given axis
* argmin : Returns the indices of the minimum values along an axis
* max : Return the maximum along a given axis
* argmax : Returns the indices of the maximum values along an axis
* sum : Return the sum of the array elements over the given axis.
* cumsum : Return the cumulative sum of the array elements over the given axis.
* prod : Return the product of the array elements over the given axis.
* mean : Returns the average of the array elements along given axis.
* std : Returns the standard deviation of the array elements along given axis.
* var : Returns the variance deviation of the array elements along given axis.
* any : Test whether any array element along a given axis evaluates to True.
* all : Test whether all array elements along a given axis evaluate to True.

Many unary operations, such as computing the sum of all the elements in the array, are also implemented as methods of the ndarray class.

In [26]:
my_2d_array = np.arange(4*3).reshape((4,3))
my_2d_array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
my_2d_array.sum() # equivalent to np.sum(my_2d_array)

66

In [28]:
my_2d_array.min() # equivalent to np.min(my_2d_array)

0

In [29]:
my_2d_array.max() # equivalent to np.max(my_2d_array)

11

In [30]:
my_2d_array.sum(axis=0) # equivalent to np.sum(my_2d_array, axis=0)
# If the original shape of the my_2d_array is (4,3), the first dimension is removed after the sumation!
# Hence, the shape of the resulting array is (3,)

array([18, 22, 26])

In [31]:
random_2D_array = np.random.random((6,3))
min_indexes = random_2D_array.argmin(axis=0) # equivalent to np.argmin(my_2d_array, axis=0)
min_indexes

array([5, 5, 5])

<a id='Indexing'></a>
# Indexing, Slicing and Iterating

In [32]:
One-dimensional arrays can be indexed sliced and iterated over, much like lists and other Python sequences.

SyntaxError: invalid syntax (<ipython-input-32-86115fec6fc0>, line 1)

In [33]:
my_1D_array = np.arange(10)**3
my_1D_array

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [34]:
my_1D_array[2] # Access the 3rd element

8

In [35]:
my_1D_array[2:5] # Return a 1D view of the array from the 2nd to the 4th element.

array([ 8, 27, 64])

In [36]:
# equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
my_1D_array[:6:2] = -1000  
my_1D_array

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [37]:
my_1D_array[ : :-1]   # reversed

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [38]:
# Iterate over the array elements. Slow!
for i in my_1D_array:
    print(i)

-1000
1
-1000
27
-1000
125
216
343
512
729


<a id='Views'></a>
# Views versus copies in NumPy

(Taken from the [scipy cookbook](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html), [License](https://github.com/scipy/scipy-cookbook/blob/master/LICENSE.txt) ).

## What is a view of a NumPy array?

As its name is saying, it is simply another way of viewing the data of the array. Technically, that means that the data of both objects is shared. You can create views by selecting a slice of the original array, or also by changing the dtype (or a combination of both). These different kinds of views are described below.

Different array objects can share the same data. The view method creates a new array object that looks at the same data.

# Slice views

This is probably the most common source of view creations in NumPy. When we slice a array, numpy return a new array that *view* the same part in memory where the original array stores the data! For example:

In [39]:
my_1D_array = np.arange(10)
print("my_1D_array=",my_1D_array)

view_1 = my_1D_array[0:5]

print("view_1=",view_1)
view_2 = my_1D_array[5:]
print("view_2=",view_2)

my_1D_array= [0 1 2 3 4 5 6 7 8 9]
view_1= [0 1 2 3 4]
view_2= [5 6 7 8 9]


In [40]:
# Now, let's modify the first element of my_1D_array.
my_1D_array[0]=-10
print("my_1D_array=",my_1D_array)
print("view_1=",view_1)  # Here we will see the change!!
print("view_2=",view_2)


my_1D_array= [-10   1   2   3   4   5   6   7   8   9]
view_1= [-10   1   2   3   4]
view_2= [5 6 7 8 9]


In [41]:
# Now, let's modify the first element of view_1 back to 0.
view_1[0]=0
print("my_1D_array=",my_1D_array)  # Here we will see that the first elment also change!
print("view_1=",view_1) 
print("view_2=",view_2)


my_1D_array= [0 1 2 3 4 5 6 7 8 9]
view_1= [0 1 2 3 4]
view_2= [5 6 7 8 9]


In [42]:
# If we want to return a copy of the data...
copy_of_array = my_1D_array[0:5].copy()

copy_of_array[0]=-10

print("my_1D_array=",my_1D_array)  # Here we will see that the first elment also change!
print("view_1=",view_1) 
print("copy_of_array=",copy_of_array)


my_1D_array= [0 1 2 3 4 5 6 7 8 9]
view_1= [0 1 2 3 4]
copy_of_array= [-10   1   2   3   4]


# Advanced Indexing

## Integer array indexing

Integer array indexing allows selection of arbitrary items in the array based on their N-dimensional index. Each integer array represents a number of indexes into that dimension.


In [43]:
# 1D example
x = np.arange(5)
print("x=",x)
resorted_x = x[[4,3,2,1,0]]
print("resorted_x=",resorted_x)

only_even_numbers = x[[0,2,4]]
print("only_even_numbers=",resorted_x)

    

x= [0 1 2 3 4]
resorted_x= [4 3 2 1 0]
only_even_numbers= [4 3 2 1 0]


To select arbitrary elements from a 2D array, we can use a sequence of 2 sequences.

From each row, a specific element should be selected. The row index is just [0, 1, 2] and the column index specifies 
the element to choose for the corresponding row, here [0, 1, 0]. 
Using both together the task can be solved using advanced indexing:

In [44]:
my_2d_array = np.array([[1, 2], [3, 4], [5, 6]])
print("my_2d_array",my_2d_array)
print("my_2d_array.shape",my_2d_array.shape)

print("My selection:",my_2d_array[[0, 1, 2], [0, 1, 0]])


my_2d_array [[1 2]
 [3 4]
 [5 6]]
my_2d_array.shape (3, 2)
My selection: [1 4 5]


## Combining advanced and basic indexing

When there is at least one slice (:), ellipsis (...) or np.newaxis in the index (or the array has more dimensions than there are advanced indexes), then the behaviour can be more complicated. It is like concatenating the indexing result for each advanced index element



In [45]:
print("my_2d_array",my_2d_array)
print("My selection:",my_2d_array[[0, 2],:])

my_2d_array [[1 2]
 [3 4]
 [5 6]]
My selection: [[1 2]
 [5 6]]


## Boolean array indexing

This advanced indexing occurs when indexing element is an array object of Boolean type, such as may be returned from comparison operators.

If obj.ndim == x.ndim, x[bool_array] returns a 1-dimensional array filled with the elements of x corresponding to the True values of bool_array.
If obj has True values at entries that are outside of the bounds of x (different shape), then an index error will be raised. If bool_array is smaller than x it is identical to filling it with False.

**Better if you use the bools of the same shape!**

### Example

A common use case for this is filtering for desired element values. For example one may wish to select all entries from an array which are not NaN:


In [46]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
print("x",x, '\n')
print("x.shape=",x.shape)

x[~np.isnan(x)]

x [[  1.   2.]
 [ nan   3.]
 [ nan  nan]] 

x.shape= (3, 2)


array([ 1.,  2.,  3.])

Or wish to add a constant to all negative elements:

In [47]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([  1.,  19.,  18.,   3.])

# Exercises

## 1) The dataset include the grades of 200 students for 4 different exams (a 2D array).
### a) Compute the mean, max, min, and the std for each of the exams.

In [48]:
# Lets create random grades first
np.random.seed(0) # Lets specify the seed so everyone use the same values.

mean_grades_per_exam = 50 + np.random.rand(4)*50
standard_deviations_per_exam  = 10 + np.random.rand(4)

grades = np.random.randn(200,4)

grades = mean_grades_per_exam[np.newaxis,:] + grades*standard_deviations_per_exam[np.newaxis,:]

grades = np.around(grades, decimals=1) # Keep only one decimal point

grades[grades<0]=0
grades[grades>100]=100


# Now that we have the grades created, you can compute the statistics per exam.
# The mean, max, min, and the std.


### b) Count how many students fail each exam (grades lower than 60%).

## 2) The dataset contains the grades (from 0 to 100) of the students stored in a dictionary (the student id is the dictionary key). 
### a) Print the total number of students

In [49]:
# Lets first load the data from the repository

# Snippet adapted from:
# https://stackoverflow.com/questions/12965203/how-to-get-json-from-webpage-into-python-script

#The urllib.request module defines functions and classes which help in opening URLs (mostly HTTP).
import urllib.request

import json #json file parser

# We will only use the urljoin function that construct a full (“absolute”) URL 
# by combining a “base URL” (base) with another URL (url).

repository_url="https://raw.githubusercontent.com/aperezhortal/PythonWorkshopsOnDataScience/master/datasets/student_grades/"
   
# For testing: repository_url="http://127.0.0.1:8000/"

print("Loading dictionaries from "+repository_url)
dict_url = repository_url +  "grades_by_id.json"
    
with urllib.request.urlopen(dict_url) as data_url:        
    grades_by_id = json.loads(data_url.read().decode())
print("grades_by_id loaded")
    
# Now, write your code here:
# The following dict is available with the data
#   grades_by_id




Loading dictionaries from https://raw.githubusercontent.com/aperezhortal/PythonWorkshopsOnDataScience/master/datasets/student_grades/
grades_by_id loaded


### b) Store the students grades in an array.

### c) Print the the average grades.

## 3) A not numpy exercise :P 
## The students's names, ids, age, and grades are distributed in the different dictionaries. 
### a) Print the total number of students
### b) Print the total number of students for each alphabetical letter.
### c) Store the students grades in a dictionaries that use the **student full name** as key.
### d) Print the the average grades by age.

The following dictionaries with data are available:
* **id_by_name**: A dictionary that store each student id using the names as keys.
* **ages_by_name**: A dictionary that store each student id using the names as keys.
* **grades_by_id**: A dictionary that store each student id using the names as keys.

The alphabet is stored in the module ascii_lowercase in the **string** package.
https://docs.python.org/3/library/string.html

In [50]:
# Lets first load the data from the repository

# Snippet adapted from:
# https://stackoverflow.com/questions/12965203/how-to-get-json-from-webpage-into-python-script

#The urllib.request module defines functions and classes which help in opening URLs (mostly HTTP).
import urllib.request

import json #json file parser

# We will only use the urljoin function that construct a full (“absolute”) URL 
# by combining a “base URL” (base) with another URL (url).

my_dictionaries_names = [ "id_by_name", "ages_by_name", "grades_by_id"]
repository_url="https://raw.githubusercontent.com/aperezhortal/PythonWorkshopsOnDataScience/master/datasets/student_grades/"

    
# For testing: repository_url="http://127.0.0.1:8000/"

print("Loading dictionaries from "+repository_url)
for my_dict_name in my_dictionaries_names:    
    
    dict_url = repository_url + my_dict_name + ".json"
    
    with urllib.request.urlopen(dict_url) as data_url:
        
        my_dict_instance = json.loads(data_url.read().decode())
        exec(my_dict_name+"=my_dict_instance")
        print("* " + my_dict_name + " loaded")
    
# Now, write your code here:
# The following dicts are available:
#   id_by_name
#   ages_by_name
#   grades_by_id


Loading dictionaries from https://raw.githubusercontent.com/aperezhortal/PythonWorkshopsOnDataScience/master/datasets/student_grades/
* id_by_name loaded
* ages_by_name loaded
* grades_by_id loaded


<a id='License'></a>
# License


This notebook it is released under the same license as NumPy, licensed under the BSD license, enabling reuse with few restrictions.

[Numpy License](http://www.numpy.org/license.html)

[scipy cookbook License](https://github.com/scipy/scipy-cookbook/blob/master/LICENSE.txt)

# Credits

Most of the content of this notebook was taken from the Numpy's quickstart tutorial from the official documentation.
https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html 

The section **Views versus copies in NumPy** was adapted from the [scipy cookbook](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html).
